/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Loick ADJIWANOU
 */
public class Fenetre extends javax.swing.JFrame {

    /**
     * Creates new form Voiture
     */
    public Fenetre() {
        
        initComponents();
        //Affichage();
    }

    
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        numSerie = new javax.swing.JTextField();
        marque = new javax.swing.JTextField();
        modele = new javax.swing.JTextField();
        couleur = new javax.swing.JTextField();
        prixVente = new javax.swing.JTextField();
        prixAchat = new javax.swing.JTextField();
        validerVoiture = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nomClient = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        validerClient = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nomCaissier = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        idVente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dateVente = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        prix = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        validerCV = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Charger = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        recherche = new javax.swing.JTextField();
        rec = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        calculer = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table4 = new javax.swing.JTable();
        meilleursClients = new javax.swing.JToggleButton();
        Text = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("VOITURE");

        jLabel5.setText("Num Série:");

        jLabel6.setText("Marque:");

        jLabel7.setText("Modèle:");

        jLabel8.setText("Couleur:");

        jLabel9.setText("Prix Achat:");

        jLabel10.setText("Prix Vente:");

        numSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSerieActionPerformed(evt);
            }
        });

        validerVoiture.setBackground(new java.awt.Color(255, 255, 255));
        validerVoiture.setText("Valider");
        validerVoiture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerVoitureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numSerie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(marque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modele, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(couleur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prixAchat, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(prixVente))))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(validerVoiture)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(couleur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prixAchat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(prixVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(validerVoiture)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 310));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CLIENT");

        jLabel11.setText("Nom:");

        jLabel12.setText("Email:");

        jLabel13.setText("Téléphone:");

        validerClient.setBackground(new java.awt.Color(255, 255, 255));
        validerClient.setText("Valider");
        validerClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(121, 121, 121)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(nomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(validerClient)))
                .addGap(11, 11, 11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(validerClient)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 190, 310));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CAISSIER");

        jLabel14.setText("Nom:");

        jLabel17.setText("Id Vente:");

        jLabel15.setText("Date Vente:");

        dateVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateVenteActionPerformed(evt);
            }
        });

        jLabel16.setText("Prix:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("VENTE");

        validerCV.setBackground(new java.awt.Color(255, 255, 255));
        validerCV.setText("Valider");
        validerCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerCVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(validerCV))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomCaissier, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel17))
                            .addComponent(jLabel15)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idVente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateVente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(idVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomCaissier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(dateVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(validerCV, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 310, 310));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Série", "Marque", "Modèle", "Couleur", "Prix Achat", "Prix Vente"
            }
        ));
        jScrollPane2.setViewportView(Table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 39, 558, 114));

        Charger.setText("Charger");
        Charger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChargerActionPerformed(evt);
            }
        });
        getContentPane().add(Charger, new org.netbeans.lib.awtextra.AbsoluteConstraints(999, 159, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("RECHERCHER UNE VOITURE PAR LE NUMÉRO DE SÉRIE");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Série", "Marque", "Modèle", "Couleur", "Prix Achat", "Prix Vente"
            }
        ));
        jScrollPane3.setViewportView(Table1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 720, 114));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Entrez le numéro de série:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheActionPerformed(evt);
            }
        });
        getContentPane().add(recherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 126, -1));

        rec.setText("Rechercher");
        rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recActionPerformed(evt);
            }
        });
        getContentPane().add(rec, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("CALCUL DU BÉNÉFICE SUR LES VENTES");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(876, 259, -1, -1));

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Série", "Prix Achat", "Prix Vente"
            }
        ));
        jScrollPane1.setViewportView(Table2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 322, 429, 139));

        calculer.setText("Calculer");
        calculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculerActionPerformed(evt);
            }
        });
        getContentPane().add(calculer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 480, -1, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("VOITURES EN STOCK");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(941, 4, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("MEILLEURS CLIENTS DU PARC");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, -1, -1));

        Table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Email", "Téléphone"
            }
        ));
        jScrollPane4.setViewportView(Table4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 730, 100));

        meilleursClients.setText("Charger");
        meilleursClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meilleursClientsActionPerformed(evt);
            }
        });
        getContentPane().add(meilleursClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 690, -1, -1));
        getContentPane().add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 110, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Bénéfice Total :");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numSerieActionPerformed

    private void validerVoitureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerVoitureActionPerformed
        // TODO add your handling code here:
        try{
            String numSerieSaisi = numSerie.getText();
            String marqueSaisi = marque.getText();
            String modeleSaisi = modele.getText();
            String couleurSaisi = couleur.getText();
            String p1 = prixAchat.getText();
            double prixAchatSaisi = Double.parseDouble(p1);
            String p2 = prixVente.getText();
            double prixVenteSaisi = Double.parseDouble(p2);
            
            
            Class.forName("org.postgresql.Driver");
            String url = "jdbc:postgresql://localhost:5432/Esgis";
            String user = "postgres";
            String passwd = "azerty21";
            Connection conn = DriverManager.getConnection(url, user, passwd);
            String requete = "INSERT INTO voiture(numSerie, marque, modele, couleur, prixAchat, prixVente) VALUES(?,?,?,?,?,?)";
            pst = conn.prepareStatement(requete);
            pst.setString(1, numSerieSaisi);
            pst.setString(2, marqueSaisi);
            pst.setString(3, modeleSaisi);
            pst.setString(4, couleurSaisi);
            pst.setDouble(5, prixAchatSaisi);
            pst.setDouble(6, prixVenteSaisi);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Données voiture enregistrés avec succès !");
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_validerVoitureActionPerformed

    private void validerClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerClientActionPerformed
        // TODO add your handling code here:
        try{
            String nomClientSaisi = nomClient.getText();
            String emailSaisi = email.getText();
            String telephoneSaisi = telephone.getText();
            
            Class.forName("org.postgresql.Driver");
            String url = "jdbc:postgresql://localhost:5432/Esgis";
            String user = "postgres";
            String passwd = "azerty21";
            Connection conn = DriverManager.getConnection(url, user, passwd);
            
            String requete = "INSERT INTO client(name, email, telephone) VALUES(?,?,?)";
            pst = conn.prepareStatement(requete);
            pst.setString(1, nomClientSaisi);
            pst.setString(2, emailSaisi);
            pst.setString(3, telephoneSaisi);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Données client enregistrés avec succès !");
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_validerClientActionPerformed

    private void validerCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerCVActionPerformed
        // TODO add your handling code here:
        try{
            String nomCaissierSaisi = nomCaissier.getText();
            String idVenteSaisi = idVente.getText();
            String dateVenteSaisi = dateVente.getText();
            String p = prix.getText();
            double prixSaisi = Double.parseDouble(p);
            
            Class.forName("org.postgresql.Driver");
            String url = "jdbc:postgresql://localhost:5432/Esgis";
            String user = "postgres";
            String passwd = "azerty21";
            Connection conn = DriverManager.getConnection(url, user, passwd);
            
            String requete = "INSERT INTO caissier(name) VALUES(?)";
            pst = conn.prepareStatement(requete);
            pst.setString(1, nomCaissierSaisi);
            pst.executeUpdate();
            String req = "INSERT INTO vente(idVente, dateVente, prix) VALUES(?,?,?)";
            pst = conn.prepareStatement(req);
            pst.setString(1, idVenteSaisi);
            pst.setString(2, dateVenteSaisi);
            pst.setDouble(3, prixSaisi);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Données vente et caissier enregistrés avec succès !");
          
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_validerCVActionPerformed

    private void dateVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateVenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateVenteActionPerformed

    private void ChargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChargerActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("org.postgresql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Esgis","postgres","azerty21");
            Statement st = conn.createStatement();
            String requ = "SELECT numSerie, marque, modele, couleur, prixAchat, prixVente FROM voiture";
            ResultSet rs = st.executeQuery(requ);
            
            while(rs.next()){
                String nSerie = String.valueOf(rs.getString("numSerie"));
                String marq = String.valueOf(rs.getString("marque"));
                String model = String.valueOf(rs.getString("modele"));
                String coul = String.valueOf(rs.getString("couleur"));
                String pAchat = String.valueOf(rs.getDouble("prixAchat"));
                String pVente = String.valueOf(rs.getDouble("prixVente"));
                
                String tbData[] = {nSerie, marq, model, coul, pAchat, pVente};
                DefaultTableModel tb1Model = (DefaultTableModel)Table.getModel();
                
                tb1Model.addRow(tbData);
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ChargerActionPerformed

    private void rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheActionPerformed

    }//GEN-LAST:event_rechercheActionPerformed

    private void recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recActionPerformed
        // TODO add your handling code here:
        try {                                          
            // TODO add your handling code here:
            String rechercheSaisi = recherche.getText();
            try {
                Class.forName("org.postgresql.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
            }
            String url = "jdbc:postgresql://localhost:5432/Esgis";
            String user = "postgres";
            String passwd = "azerty21";
            Connection conn = DriverManager.getConnection(url, user, passwd);

            Statement st = conn.createStatement();
            String reque = "SELECT numSerie, marque, modele, couleur, prixAchat, prixVente FROM voiture WHERE numSerie = ?";
            pst = conn.prepareStatement(reque);
            pst.setString(1, rechercheSaisi);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String nSerie = String.valueOf(rs.getString("numSerie"));
                String marq = String.valueOf(rs.getString("marque"));
                String model = String.valueOf(rs.getString("modele"));
                String coul = String.valueOf(rs.getString("couleur"));
                String pAchat = String.valueOf(rs.getDouble("prixAchat"));
                String pVente = String.valueOf(rs.getDouble("prixVente"));
                
                String tbData[] = {nSerie, marq, model, coul, pAchat, pVente};
                DefaultTableModel tb1Model = (DefaultTableModel)Table1.getModel();
                
                tb1Model.addRow(tbData);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_recActionPerformed

    private void calculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculerActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("org.postgresql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Esgis","postgres","azerty21");
            Statement st = conn.createStatement();
            String requ = "SELECT numSerie, prixAchat, prixVente FROM voiture";
            ResultSet rs = st.executeQuery(requ);
            
            while(rs.next()){
                String nSerie = String.valueOf(rs.getString("numSerie"));
                String pAchat = String.valueOf(rs.getDouble("prixAchat"));
                String pVente = String.valueOf(rs.getDouble("prixVente"));
                
                String tbData[] = {nSerie, pAchat, pVente};
                DefaultTableModel tb1Model = (DefaultTableModel)Table2.getModel();
                
                tb1Model.addRow(tbData);
                
            }
            
            double profit = 0.0, profitTotal = 0.0;
            while(rs.next()){
                double pAchat = Double.valueOf(rs.getDouble("prixAchat"));
                double pVente = Double.valueOf(rs.getDouble("prixVente"));
            
                profit = (double)(pVente) - (double)(pAchat);
                profitTotal = profitTotal + profit;
                
            }
            Text.setText(""+profitTotal);
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_calculerActionPerformed

    private void meilleursClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meilleursClientsActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("org.postgresql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Esgis","postgres","azerty21");
            Statement st = conn.createStatement();
            String requee = "SELECT * FROM client";
            rs = st.executeQuery(requee);
            
            while(rs.next()){
                String cNom = String.valueOf(rs.getString("name"));
                String cEmail = String.valueOf(rs.getString("Email"));
                String cTelephone = String.valueOf(rs.getString("Telephone"));
                
                String tbData[] = {cNom, cEmail, cTelephone};
                DefaultTableModel tb1Model = (DefaultTableModel)Table4.getModel();
                
                tb1Model.addRow(tbData);
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_meilleursClientsActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Charger;
    private javax.swing.JTable Table;
    private javax.swing.JTable Table1;
    private javax.swing.JTable Table2;
    private javax.swing.JTable Table4;
    private javax.swing.JTextField Text;
    private javax.swing.JButton calculer;
    private javax.swing.JTextField couleur;
    private javax.swing.JTextField dateVente;
    private javax.swing.JTextField email;
    private javax.swing.JTextField idVente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField marque;
    private javax.swing.JToggleButton meilleursClients;
    private javax.swing.JTextField modele;
    private javax.swing.JTextField nomCaissier;
    private javax.swing.JTextField nomClient;
    private javax.swing.JTextField numSerie;
    private javax.swing.JTextField prix;
    private javax.swing.JTextField prixAchat;
    private javax.swing.JTextField prixVente;
    private javax.swing.JButton rec;
    private javax.swing.JTextField recherche;
    private javax.swing.JTextField telephone;
    private javax.swing.JButton validerCV;
    private javax.swing.JButton validerClient;
    private javax.swing.JButton validerVoiture;
    // End of variables declaration//GEN-END:variables
}
